<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use App\Models\Office;
use App\Models\WorkPlace;

class OfficeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('offices')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $data = array(
            array('incrementId' => '1','workPlaceIncrementId' => '11','officeNo' => 'W10000','higherOfficeId' => NULL,'districtId' => NULL,'provinceId' => '7','officeTypeId' => '1','active' => '1'),
            array('incrementId' => '2','workPlaceIncrementId' => '12','officeNo' => 'W20000','higherOfficeId' => NULL,'districtId' => NULL,'provinceId' => '5','officeTypeId' => '1','active' => '1'),
            array('incrementId' => '3','workPlaceIncrementId' => '13','officeNo' => 'W30000','higherOfficeId' => NULL,'districtId' => NULL,'provinceId' => '6','officeTypeId' => '1','active' => '1'),
            array('incrementId' => '4','workPlaceIncrementId' => '14','officeNo' => 'W40000','higherOfficeId' => NULL,'districtId' => NULL,'provinceId' => '1','officeTypeId' => '1','active' => '1'),
            array('incrementId' => '5','workPlaceIncrementId' => '15','officeNo' => 'W50000','higherOfficeId' => NULL,'districtId' => NULL,'provinceId' => '4','officeTypeId' => '1','active' => '1'),
            array('incrementId' => '6','workPlaceIncrementId' => '16','officeNo' => 'W60000','higherOfficeId' => NULL,'districtId' => NULL,'provinceId' => '9','officeTypeId' => '1','active' => '1'),
            array('incrementId' => '7','workPlaceIncrementId' => '17','officeNo' => 'W70000','higherOfficeId' => NULL,'districtId' => NULL,'provinceId' => '8','officeTypeId' => '1','active' => '1'),
            array('incrementId' => '8','workPlaceIncrementId' => '18','officeNo' => 'W80000','higherOfficeId' => NULL,'districtId' => NULL,'provinceId' => '3','officeTypeId' => '1','active' => '1'),
            array('incrementId' => '9','workPlaceIncrementId' => '19','officeNo' => 'W90000','higherOfficeId' => NULL,'districtId' => NULL,'provinceId' => '2','officeTypeId' => '1','active' => '1'),
            array('incrementId' => '10','workPlaceIncrementId' => '20','officeNo' => 'W10100','higherOfficeId' => '1','districtId' => '23','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '11','workPlaceIncrementId' => '21','officeNo' => 'W10101','higherOfficeId' => '10','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '12','workPlaceIncrementId' => '22','officeNo' => 'W10102','higherOfficeId' => '10','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '13','workPlaceIncrementId' => '23','officeNo' => 'W10103','higherOfficeId' => '10','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '14','workPlaceIncrementId' => '24','officeNo' => 'W10104','higherOfficeId' => '10','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '15','workPlaceIncrementId' => '25','officeNo' => 'W10200','higherOfficeId' => '1','districtId' => '23','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '16','workPlaceIncrementId' => '26','officeNo' => 'W10201','higherOfficeId' => '15','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '17','workPlaceIncrementId' => '27','officeNo' => 'W10202','higherOfficeId' => '15','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '18','workPlaceIncrementId' => '28','officeNo' => 'W10203','higherOfficeId' => '15','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '19','workPlaceIncrementId' => '29','officeNo' => 'W10300','higherOfficeId' => '1','districtId' => '23','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '20','workPlaceIncrementId' => '30','officeNo' => 'W10301','higherOfficeId' => '19','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '21','workPlaceIncrementId' => '31','officeNo' => 'W10302','higherOfficeId' => '19','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '22','workPlaceIncrementId' => '32','officeNo' => 'W10303','higherOfficeId' => '19','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '23','workPlaceIncrementId' => '33','officeNo' => 'W10304','higherOfficeId' => '19','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '24','workPlaceIncrementId' => '34','officeNo' => 'W10400','higherOfficeId' => '1','districtId' => '23','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '25','workPlaceIncrementId' => '35','officeNo' => 'W10401','higherOfficeId' => '24','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '26','workPlaceIncrementId' => '36','officeNo' => 'W10402','higherOfficeId' => '24','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '27','workPlaceIncrementId' => '37','officeNo' => 'W10403','higherOfficeId' => '24','districtId' => '23','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '28','workPlaceIncrementId' => '38','officeNo' => 'W10500','higherOfficeId' => '1','districtId' => '22','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '29','workPlaceIncrementId' => '39','officeNo' => 'W10501','higherOfficeId' => '28','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '30','workPlaceIncrementId' => '40','officeNo' => 'W10502','higherOfficeId' => '28','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '31','workPlaceIncrementId' => '41','officeNo' => 'W10503','higherOfficeId' => '28','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '32','workPlaceIncrementId' => '42','officeNo' => 'W10600','higherOfficeId' => '1','districtId' => '22','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '33','workPlaceIncrementId' => '43','officeNo' => 'W10601','higherOfficeId' => '32','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '34','workPlaceIncrementId' => '44','officeNo' => 'W10602','higherOfficeId' => '32','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '35','workPlaceIncrementId' => '45','officeNo' => 'W10603','higherOfficeId' => '32','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '36','workPlaceIncrementId' => '46','officeNo' => 'W10700','higherOfficeId' => '1','districtId' => '22','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '37','workPlaceIncrementId' => '47','officeNo' => 'W10701','higherOfficeId' => '36','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '38','workPlaceIncrementId' => '48','officeNo' => 'W10702','higherOfficeId' => '36','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '39','workPlaceIncrementId' => '49','officeNo' => 'W10703','higherOfficeId' => '36','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '40','workPlaceIncrementId' => '50','officeNo' => 'W10800','higherOfficeId' => '1','districtId' => '22','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '41','workPlaceIncrementId' => '51','officeNo' => 'W10801','higherOfficeId' => '40','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '42','workPlaceIncrementId' => '52','officeNo' => 'W10802','higherOfficeId' => '40','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '43','workPlaceIncrementId' => '53','officeNo' => 'W10803','higherOfficeId' => '40','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '44','workPlaceIncrementId' => '54','officeNo' => 'W10804','higherOfficeId' => '40','districtId' => '22','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '45','workPlaceIncrementId' => '55','officeNo' => 'W10900','higherOfficeId' => '1','districtId' => '21','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '46','workPlaceIncrementId' => '56','officeNo' => 'W10901','higherOfficeId' => '45','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '47','workPlaceIncrementId' => '57','officeNo' => 'W10902','higherOfficeId' => '45','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '48','workPlaceIncrementId' => '58','officeNo' => 'W10903','higherOfficeId' => '45','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '49','workPlaceIncrementId' => '59','officeNo' => 'W10904','higherOfficeId' => '45','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '50','workPlaceIncrementId' => '60','officeNo' => 'W11000','higherOfficeId' => '1','districtId' => '21','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '51','workPlaceIncrementId' => '61','officeNo' => 'W11001','higherOfficeId' => '50','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '52','workPlaceIncrementId' => '62','officeNo' => 'W11002','higherOfficeId' => '50','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '53','workPlaceIncrementId' => '63','officeNo' => 'W11003','higherOfficeId' => '50','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '54','workPlaceIncrementId' => '64','officeNo' => 'W11004','higherOfficeId' => '50','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '55','workPlaceIncrementId' => '65','officeNo' => 'W11100','higherOfficeId' => '1','districtId' => '21','provinceId' => '7','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '56','workPlaceIncrementId' => '66','officeNo' => 'W11101','higherOfficeId' => '55','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '57','workPlaceIncrementId' => '67','officeNo' => 'W11102','higherOfficeId' => '55','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '58','workPlaceIncrementId' => '68','officeNo' => 'W11103','higherOfficeId' => '55','districtId' => '21','provinceId' => '7','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '59','workPlaceIncrementId' => '69','officeNo' => 'W20100','higherOfficeId' => '2','districtId' => '3','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '60','workPlaceIncrementId' => '70','officeNo' => 'W20101','higherOfficeId' => '59','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '61','workPlaceIncrementId' => '71','officeNo' => 'W20102','higherOfficeId' => '59','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '62','workPlaceIncrementId' => '72','officeNo' => 'W20200','higherOfficeId' => '2','districtId' => '3','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '63','workPlaceIncrementId' => '73','officeNo' => 'W20201','higherOfficeId' => '62','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '64','workPlaceIncrementId' => '74','officeNo' => 'W20202','higherOfficeId' => '62','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '65','workPlaceIncrementId' => '75','officeNo' => 'W20300','higherOfficeId' => '2','districtId' => '3','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '66','workPlaceIncrementId' => '76','officeNo' => 'W20301','higherOfficeId' => '65','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '67','workPlaceIncrementId' => '77','officeNo' => 'W20302','higherOfficeId' => '65','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '68','workPlaceIncrementId' => '78','officeNo' => 'W20303','higherOfficeId' => '65','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '69','workPlaceIncrementId' => '79','officeNo' => 'W20400','higherOfficeId' => '2','districtId' => '3','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '70','workPlaceIncrementId' => '80','officeNo' => 'W20401','higherOfficeId' => '69','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '71','workPlaceIncrementId' => '81','officeNo' => 'W20402','higherOfficeId' => '69','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '72','workPlaceIncrementId' => '82','officeNo' => 'W20403','higherOfficeId' => '69','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '73','workPlaceIncrementId' => '83','officeNo' => 'W20500','higherOfficeId' => '2','districtId' => '3','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '74','workPlaceIncrementId' => '84','officeNo' => 'W20501','higherOfficeId' => '73','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '75','workPlaceIncrementId' => '85','officeNo' => 'W20502','higherOfficeId' => '73','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '76','workPlaceIncrementId' => '86','officeNo' => 'W20503','higherOfficeId' => '73','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '77','workPlaceIncrementId' => '87','officeNo' => 'W20600','higherOfficeId' => '2','districtId' => '3','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '78','workPlaceIncrementId' => '88','officeNo' => 'W20601','higherOfficeId' => '77','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '79','workPlaceIncrementId' => '89','officeNo' => 'W20602','higherOfficeId' => '77','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '80','workPlaceIncrementId' => '90','officeNo' => 'W20603','higherOfficeId' => '77','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '81','workPlaceIncrementId' => '91','officeNo' => 'W20604','higherOfficeId' => '77','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '82','workPlaceIncrementId' => '92','officeNo' => 'W20605','higherOfficeId' => '77','districtId' => '3','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '83','workPlaceIncrementId' => '93','officeNo' => 'W20700','higherOfficeId' => '2','districtId' => '2','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '84','workPlaceIncrementId' => '94','officeNo' => 'W20701','higherOfficeId' => '83','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '85','workPlaceIncrementId' => '95','officeNo' => 'W20702','higherOfficeId' => '83','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '86','workPlaceIncrementId' => '96','officeNo' => 'W20703','higherOfficeId' => '83','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '87','workPlaceIncrementId' => '97','officeNo' => 'W20704','higherOfficeId' => '83','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '88','workPlaceIncrementId' => '98','officeNo' => 'W20800','higherOfficeId' => '2','districtId' => '2','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '89','workPlaceIncrementId' => '99','officeNo' => 'W20801','higherOfficeId' => '88','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '90','workPlaceIncrementId' => '100','officeNo' => 'W20802','higherOfficeId' => '88','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '91','workPlaceIncrementId' => '101','officeNo' => 'W20803','higherOfficeId' => '88','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '92','workPlaceIncrementId' => '102','officeNo' => 'W20900','higherOfficeId' => '2','districtId' => '2','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '93','workPlaceIncrementId' => '103','officeNo' => 'W20901','higherOfficeId' => '92','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '94','workPlaceIncrementId' => '104','officeNo' => 'W20902','higherOfficeId' => '92','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '95','workPlaceIncrementId' => '105','officeNo' => 'W21000','higherOfficeId' => '2','districtId' => '2','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '96','workPlaceIncrementId' => '106','officeNo' => 'W21001','higherOfficeId' => '95','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '97','workPlaceIncrementId' => '107','officeNo' => 'W21002','higherOfficeId' => '95','districtId' => '2','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '98','workPlaceIncrementId' => '108','officeNo' => 'W21100','higherOfficeId' => '2','districtId' => '1','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '99','workPlaceIncrementId' => '109','officeNo' => 'W21101','higherOfficeId' => '98','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '100','workPlaceIncrementId' => '110','officeNo' => 'W21102','higherOfficeId' => '98','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '101','workPlaceIncrementId' => '111','officeNo' => 'W21103','higherOfficeId' => '98','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '102','workPlaceIncrementId' => '112','officeNo' => 'W21104','higherOfficeId' => '98','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '103','workPlaceIncrementId' => '113','officeNo' => 'W21200','higherOfficeId' => '2','districtId' => '1','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '104','workPlaceIncrementId' => '114','officeNo' => 'W21201','higherOfficeId' => '103','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '105','workPlaceIncrementId' => '115','officeNo' => 'W21300','higherOfficeId' => '2','districtId' => '1','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '106','workPlaceIncrementId' => '116','officeNo' => 'W21301','higherOfficeId' => '105','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '107','workPlaceIncrementId' => '117','officeNo' => 'W21302','higherOfficeId' => '105','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '108','workPlaceIncrementId' => '118','officeNo' => 'W21303','higherOfficeId' => '105','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '109','workPlaceIncrementId' => '119','officeNo' => 'W21304','higherOfficeId' => '105','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '110','workPlaceIncrementId' => '120','officeNo' => 'W21400','higherOfficeId' => '2','districtId' => '1','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '111','workPlaceIncrementId' => '121','officeNo' => 'W21401','higherOfficeId' => '110','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '112','workPlaceIncrementId' => '122','officeNo' => 'W21500','higherOfficeId' => '2','districtId' => '1','provinceId' => '5','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '113','workPlaceIncrementId' => '123','officeNo' => 'W21501','higherOfficeId' => '112','districtId' => '1','provinceId' => '5','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '114','workPlaceIncrementId' => '124','officeNo' => 'W30100','higherOfficeId' => '3','districtId' => '19','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '115','workPlaceIncrementId' => '125','officeNo' => 'W30101','higherOfficeId' => '114','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '116','workPlaceIncrementId' => '126','officeNo' => 'W30102','higherOfficeId' => '114','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '117','workPlaceIncrementId' => '127','officeNo' => 'W30103','higherOfficeId' => '114','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '118','workPlaceIncrementId' => '128','officeNo' => 'W30104','higherOfficeId' => '114','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '119','workPlaceIncrementId' => '129','officeNo' => 'W30200','higherOfficeId' => '3','districtId' => '19','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '120','workPlaceIncrementId' => '130','officeNo' => 'W30201','higherOfficeId' => '119','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '121','workPlaceIncrementId' => '131','officeNo' => 'W30202','higherOfficeId' => '119','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '122','workPlaceIncrementId' => '132','officeNo' => 'W30203','higherOfficeId' => '119','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '123','workPlaceIncrementId' => '133','officeNo' => 'W30204','higherOfficeId' => '119','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '124','workPlaceIncrementId' => '134','officeNo' => 'W30205','higherOfficeId' => '119','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '125','workPlaceIncrementId' => '135','officeNo' => 'W30300','higherOfficeId' => '3','districtId' => '19','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '126','workPlaceIncrementId' => '136','officeNo' => 'W30301','higherOfficeId' => '125','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '127','workPlaceIncrementId' => '137','officeNo' => 'W30302','higherOfficeId' => '125','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '128','workPlaceIncrementId' => '138','officeNo' => 'W30303','higherOfficeId' => '125','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '129','workPlaceIncrementId' => '139','officeNo' => 'W30400','higherOfficeId' => '3','districtId' => '19','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '130','workPlaceIncrementId' => '140','officeNo' => 'W30401','higherOfficeId' => '129','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '131','workPlaceIncrementId' => '141','officeNo' => 'W30402','higherOfficeId' => '129','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '132','workPlaceIncrementId' => '142','officeNo' => 'W30403','higherOfficeId' => '129','districtId' => '19','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '133','workPlaceIncrementId' => '143','officeNo' => 'W30500','higherOfficeId' => '3','districtId' => '17','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '134','workPlaceIncrementId' => '144','officeNo' => 'W30501','higherOfficeId' => '133','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '135','workPlaceIncrementId' => '145','officeNo' => 'W30502','higherOfficeId' => '133','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '136','workPlaceIncrementId' => '146','officeNo' => 'W30503','higherOfficeId' => '133','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '137','workPlaceIncrementId' => '147','officeNo' => 'W30504','higherOfficeId' => '133','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '138','workPlaceIncrementId' => '148','officeNo' => 'W30600','higherOfficeId' => '3','districtId' => '17','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '139','workPlaceIncrementId' => '149','officeNo' => 'W30601','higherOfficeId' => '138','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '140','workPlaceIncrementId' => '150','officeNo' => 'W30602','higherOfficeId' => '138','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '141','workPlaceIncrementId' => '151','officeNo' => 'W30603','higherOfficeId' => '138','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '142','workPlaceIncrementId' => '152','officeNo' => 'W30700','higherOfficeId' => '3','districtId' => '17','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '143','workPlaceIncrementId' => '153','officeNo' => 'W30701','higherOfficeId' => '142','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '144','workPlaceIncrementId' => '154','officeNo' => 'W30702','higherOfficeId' => '142','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '145','workPlaceIncrementId' => '155','officeNo' => 'W30703','higherOfficeId' => '142','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '146','workPlaceIncrementId' => '156','officeNo' => 'W30704','higherOfficeId' => '142','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '147','workPlaceIncrementId' => '157','officeNo' => 'W30800','higherOfficeId' => '3','districtId' => '17','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '148','workPlaceIncrementId' => '158','officeNo' => 'W30801','higherOfficeId' => '147','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '149','workPlaceIncrementId' => '159','officeNo' => 'W30802','higherOfficeId' => '147','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '150','workPlaceIncrementId' => '160','officeNo' => 'W30803','higherOfficeId' => '147','districtId' => '17','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '151','workPlaceIncrementId' => '161','officeNo' => 'W30900','higherOfficeId' => '3','districtId' => '18','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '152','workPlaceIncrementId' => '162','officeNo' => 'W30901','higherOfficeId' => '151','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '153','workPlaceIncrementId' => '163','officeNo' => 'W30902','higherOfficeId' => '151','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '154','workPlaceIncrementId' => '164','officeNo' => 'W30903','higherOfficeId' => '151','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '155','workPlaceIncrementId' => '165','officeNo' => 'W31000','higherOfficeId' => '3','districtId' => '18','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '156','workPlaceIncrementId' => '166','officeNo' => 'W31001','higherOfficeId' => '155','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '157','workPlaceIncrementId' => '167','officeNo' => 'W31002','higherOfficeId' => '155','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '158','workPlaceIncrementId' => '168','officeNo' => 'W31003','higherOfficeId' => '155','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '159','workPlaceIncrementId' => '169','officeNo' => 'W31004','higherOfficeId' => '155','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '160','workPlaceIncrementId' => '170','officeNo' => 'W31005','higherOfficeId' => '155','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '161','workPlaceIncrementId' => '171','officeNo' => 'W31100','higherOfficeId' => '3','districtId' => '18','provinceId' => '6','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '162','workPlaceIncrementId' => '172','officeNo' => 'W31101','higherOfficeId' => '161','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '163','workPlaceIncrementId' => '173','officeNo' => 'W31102','higherOfficeId' => '161','districtId' => '18','provinceId' => '6','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '164','workPlaceIncrementId' => '174','officeNo' => 'W40100','higherOfficeId' => '4','districtId' => '14','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '165','workPlaceIncrementId' => '175','officeNo' => 'W40101','higherOfficeId' => '164','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '166','workPlaceIncrementId' => '176','officeNo' => 'W40102','higherOfficeId' => '164','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '167','workPlaceIncrementId' => '177','officeNo' => 'W40103','higherOfficeId' => '164','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '168','workPlaceIncrementId' => '178','officeNo' => 'W40200','higherOfficeId' => '4','districtId' => '14','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '169','workPlaceIncrementId' => '179','officeNo' => 'W40201','higherOfficeId' => '168','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '170','workPlaceIncrementId' => '180','officeNo' => 'W40202','higherOfficeId' => '168','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '171','workPlaceIncrementId' => '181','officeNo' => 'W40203','higherOfficeId' => '168','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '172','workPlaceIncrementId' => '182','officeNo' => 'W40204','higherOfficeId' => '168','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '173','workPlaceIncrementId' => '183','officeNo' => 'W40300','higherOfficeId' => '4','districtId' => '14','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '174','workPlaceIncrementId' => '184','officeNo' => 'W40301','higherOfficeId' => '173','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '175','workPlaceIncrementId' => '185','officeNo' => 'W40400','higherOfficeId' => '4','districtId' => '14','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '176','workPlaceIncrementId' => '186','officeNo' => 'W40401','higherOfficeId' => '175','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '177','workPlaceIncrementId' => '187','officeNo' => 'W40402','higherOfficeId' => '175','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '178','workPlaceIncrementId' => '188','officeNo' => 'W40403','higherOfficeId' => '175','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '179','workPlaceIncrementId' => '189','officeNo' => 'W40404','higherOfficeId' => '175','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '180','workPlaceIncrementId' => '190','officeNo' => 'W40500','higherOfficeId' => '4','districtId' => '14','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '181','workPlaceIncrementId' => '191','officeNo' => 'W40501','higherOfficeId' => '180','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '182','workPlaceIncrementId' => '192','officeNo' => 'W40502','higherOfficeId' => '180','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '183','workPlaceIncrementId' => '193','officeNo' => 'W40503','higherOfficeId' => '180','districtId' => '14','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '184','workPlaceIncrementId' => '194','officeNo' => 'W40600','higherOfficeId' => '4','districtId' => '13','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '185','workPlaceIncrementId' => '195','officeNo' => 'W40601','higherOfficeId' => '184','districtId' => '13','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '186','workPlaceIncrementId' => '196','officeNo' => 'W40602','higherOfficeId' => '184','districtId' => '13','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '187','workPlaceIncrementId' => '197','officeNo' => 'W40603','higherOfficeId' => '184','districtId' => '13','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '188','workPlaceIncrementId' => '198','officeNo' => 'W40604','higherOfficeId' => '184','districtId' => '13','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '189','workPlaceIncrementId' => '199','officeNo' => 'W40700','higherOfficeId' => '4','districtId' => '12','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '190','workPlaceIncrementId' => '200','officeNo' => 'W40701','higherOfficeId' => '189','districtId' => '12','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '191','workPlaceIncrementId' => '201','officeNo' => 'W40702','higherOfficeId' => '189','districtId' => '12','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '192','workPlaceIncrementId' => '202','officeNo' => 'W40703','higherOfficeId' => '189','districtId' => '12','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '193','workPlaceIncrementId' => '203','officeNo' => 'W40800','higherOfficeId' => '4','districtId' => '12','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '194','workPlaceIncrementId' => '204','officeNo' => 'W40801','higherOfficeId' => '193','districtId' => '12','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '195','workPlaceIncrementId' => '205','officeNo' => 'W40802','higherOfficeId' => '193','districtId' => '12','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '196','workPlaceIncrementId' => '206','officeNo' => 'W40900','higherOfficeId' => '4','districtId' => '10','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '197','workPlaceIncrementId' => '207','officeNo' => 'W40901','higherOfficeId' => '196','districtId' => '10','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '198','workPlaceIncrementId' => '208','officeNo' => 'W40902','higherOfficeId' => '196','districtId' => '10','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '199','workPlaceIncrementId' => '209','officeNo' => 'W40903','higherOfficeId' => '196','districtId' => '10','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '200','workPlaceIncrementId' => '210','officeNo' => 'W41000','higherOfficeId' => '4','districtId' => '10','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '201','workPlaceIncrementId' => '211','officeNo' => 'W41001','higherOfficeId' => '200','districtId' => '10','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '202','workPlaceIncrementId' => '212','officeNo' => 'W41002','higherOfficeId' => '200','districtId' => '10','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '203','workPlaceIncrementId' => '213','officeNo' => 'W41100','higherOfficeId' => '4','districtId' => '11','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '204','workPlaceIncrementId' => '214','officeNo' => 'W41101','higherOfficeId' => '203','districtId' => '11','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '205','workPlaceIncrementId' => '215','officeNo' => 'W41102','higherOfficeId' => '203','districtId' => '11','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '206','workPlaceIncrementId' => '216','officeNo' => 'W41103','higherOfficeId' => '203','districtId' => '11','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '207','workPlaceIncrementId' => '217','officeNo' => 'W41200','higherOfficeId' => '4','districtId' => '11','provinceId' => '1','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '208','workPlaceIncrementId' => '218','officeNo' => 'W41201','higherOfficeId' => '207','districtId' => '11','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '209','workPlaceIncrementId' => '219','officeNo' => 'W41202','higherOfficeId' => '207','districtId' => '11','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '210','workPlaceIncrementId' => '220','officeNo' => 'W41203','higherOfficeId' => '207','districtId' => '11','provinceId' => '1','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '211','workPlaceIncrementId' => '221','officeNo' => 'W50100','higherOfficeId' => '5','districtId' => '7','provinceId' => '4','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '212','workPlaceIncrementId' => '222','officeNo' => 'W50101','higherOfficeId' => '211','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '213','workPlaceIncrementId' => '223','officeNo' => 'W50102','higherOfficeId' => '211','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '214','workPlaceIncrementId' => '224','officeNo' => 'W50103','higherOfficeId' => '211','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '215','workPlaceIncrementId' => '225','officeNo' => 'W50104','higherOfficeId' => '211','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '216','workPlaceIncrementId' => '226','officeNo' => 'W50105','higherOfficeId' => '211','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '217','workPlaceIncrementId' => '227','officeNo' => 'W50106','higherOfficeId' => '211','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '218','workPlaceIncrementId' => '228','officeNo' => 'W50200','higherOfficeId' => '5','districtId' => '7','provinceId' => '4','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '219','workPlaceIncrementId' => '229','officeNo' => 'W50201','higherOfficeId' => '218','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '220','workPlaceIncrementId' => '230','officeNo' => 'W50202','higherOfficeId' => '218','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '221','workPlaceIncrementId' => '231','officeNo' => 'W50203','higherOfficeId' => '218','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '222','workPlaceIncrementId' => '232','officeNo' => 'W50204','higherOfficeId' => '218','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '223','workPlaceIncrementId' => '233','officeNo' => 'W50300','higherOfficeId' => '5','districtId' => '7','provinceId' => '4','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '224','workPlaceIncrementId' => '234','officeNo' => 'W50301','higherOfficeId' => '223','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '225','workPlaceIncrementId' => '235','officeNo' => 'W50302','higherOfficeId' => '223','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '226','workPlaceIncrementId' => '236','officeNo' => 'W50303','higherOfficeId' => '223','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '227','workPlaceIncrementId' => '237','officeNo' => 'W50304','higherOfficeId' => '223','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '228','workPlaceIncrementId' => '238','officeNo' => 'W50305','higherOfficeId' => '223','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '229','workPlaceIncrementId' => '239','officeNo' => 'W50400','higherOfficeId' => '5','districtId' => '7','provinceId' => '4','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '230','workPlaceIncrementId' => '240','officeNo' => 'W50401','higherOfficeId' => '229','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '231','workPlaceIncrementId' => '241','officeNo' => 'W50402','higherOfficeId' => '229','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '232','workPlaceIncrementId' => '242','officeNo' => 'W50403','higherOfficeId' => '229','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '233','workPlaceIncrementId' => '243','officeNo' => 'W50500','higherOfficeId' => '5','districtId' => '7','provinceId' => '4','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '234','workPlaceIncrementId' => '244','officeNo' => 'W50501','higherOfficeId' => '233','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '235','workPlaceIncrementId' => '245','officeNo' => 'W50502','higherOfficeId' => '233','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '236','workPlaceIncrementId' => '246','officeNo' => 'W50503','higherOfficeId' => '233','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '237','workPlaceIncrementId' => '247','officeNo' => 'W50504','higherOfficeId' => '233','districtId' => '7','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '238','workPlaceIncrementId' => '248','officeNo' => 'W50600','higherOfficeId' => '5','districtId' => '6','provinceId' => '4','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '239','workPlaceIncrementId' => '249','officeNo' => 'W50601','higherOfficeId' => '238','districtId' => '6','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '240','workPlaceIncrementId' => '250','officeNo' => 'W50602','higherOfficeId' => '238','districtId' => '6','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '241','workPlaceIncrementId' => '251','officeNo' => 'W50700','higherOfficeId' => '5','districtId' => '6','provinceId' => '4','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '242','workPlaceIncrementId' => '252','officeNo' => 'W50701','higherOfficeId' => '241','districtId' => '6','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '243','workPlaceIncrementId' => '253','officeNo' => 'W50702','higherOfficeId' => '241','districtId' => '6','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '244','workPlaceIncrementId' => '254','officeNo' => 'W50703','higherOfficeId' => '241','districtId' => '6','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '245','workPlaceIncrementId' => '255','officeNo' => 'W50800','higherOfficeId' => '5','districtId' => '6','provinceId' => '4','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '246','workPlaceIncrementId' => '256','officeNo' => 'W50801','higherOfficeId' => '245','districtId' => '6','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '247','workPlaceIncrementId' => '257','officeNo' => 'W50802','higherOfficeId' => '245','districtId' => '6','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '248','workPlaceIncrementId' => '258','officeNo' => 'W50803','higherOfficeId' => '245','districtId' => '6','provinceId' => '4','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '249','workPlaceIncrementId' => '259','officeNo' => 'W60100','higherOfficeId' => '6','districtId' => '20','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '250','workPlaceIncrementId' => '260','officeNo' => 'W60101','higherOfficeId' => '249','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '251','workPlaceIncrementId' => '261','officeNo' => 'W60102','higherOfficeId' => '249','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '252','workPlaceIncrementId' => '262','officeNo' => 'W60200','higherOfficeId' => '6','districtId' => '20','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '253','workPlaceIncrementId' => '263','officeNo' => 'W60201','higherOfficeId' => '252','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '254','workPlaceIncrementId' => '264','officeNo' => 'W60202','higherOfficeId' => '252','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '255','workPlaceIncrementId' => '265','officeNo' => 'W60203','higherOfficeId' => '252','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '256','workPlaceIncrementId' => '266','officeNo' => 'W60300','higherOfficeId' => '6','districtId' => '20','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '257','workPlaceIncrementId' => '267','officeNo' => 'W60301','higherOfficeId' => '256','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '258','workPlaceIncrementId' => '268','officeNo' => 'W60302','higherOfficeId' => '256','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '259','workPlaceIncrementId' => '269','officeNo' => 'W60303','higherOfficeId' => '256','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '260','workPlaceIncrementId' => '270','officeNo' => 'W60304','higherOfficeId' => '256','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '261','workPlaceIncrementId' => '271','officeNo' => 'W60400','higherOfficeId' => '6','districtId' => '20','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '262','workPlaceIncrementId' => '272','officeNo' => 'W60401','higherOfficeId' => '261','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '263','workPlaceIncrementId' => '273','officeNo' => 'W60402','higherOfficeId' => '261','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '264','workPlaceIncrementId' => '274','officeNo' => 'W60500','higherOfficeId' => '6','districtId' => '20','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '265','workPlaceIncrementId' => '275','officeNo' => 'W60501','higherOfficeId' => '264','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '266','workPlaceIncrementId' => '276','officeNo' => 'W60502','higherOfficeId' => '264','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '267','workPlaceIncrementId' => '277','officeNo' => 'W60600','higherOfficeId' => '6','districtId' => '20','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '268','workPlaceIncrementId' => '278','officeNo' => 'W60601','higherOfficeId' => '267','districtId' => '20','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '269','workPlaceIncrementId' => '279','officeNo' => 'W60700','higherOfficeId' => '6','districtId' => '24','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '270','workPlaceIncrementId' => '280','officeNo' => 'W60701','higherOfficeId' => '269','districtId' => '24','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '271','workPlaceIncrementId' => '281','officeNo' => 'W60702','higherOfficeId' => '269','districtId' => '24','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '272','workPlaceIncrementId' => '282','officeNo' => 'W60703','higherOfficeId' => '269','districtId' => '24','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '273','workPlaceIncrementId' => '283','officeNo' => 'W60800','higherOfficeId' => '6','districtId' => '24','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '274','workPlaceIncrementId' => '284','officeNo' => 'W60801','higherOfficeId' => '273','districtId' => '24','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '275','workPlaceIncrementId' => '285','officeNo' => 'W60802','higherOfficeId' => '273','districtId' => '24','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '276','workPlaceIncrementId' => '286','officeNo' => 'W60900','higherOfficeId' => '6','districtId' => '24','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '277','workPlaceIncrementId' => '287','officeNo' => 'W60901','higherOfficeId' => '276','districtId' => '24','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '278','workPlaceIncrementId' => '288','officeNo' => 'W61000','higherOfficeId' => '6','districtId' => '24','provinceId' => '9','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '279','workPlaceIncrementId' => '289','officeNo' => 'W61001','higherOfficeId' => '278','districtId' => '24','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '280','workPlaceIncrementId' => '290','officeNo' => 'W61002','higherOfficeId' => '278','districtId' => '24','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '281','workPlaceIncrementId' => '291','officeNo' => 'W61003','higherOfficeId' => '278','districtId' => '24','provinceId' => '9','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '282','workPlaceIncrementId' => '292','officeNo' => 'W70100','higherOfficeId' => '7','districtId' => '5','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '283','workPlaceIncrementId' => '293','officeNo' => 'W70101','higherOfficeId' => '282','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '284','workPlaceIncrementId' => '294','officeNo' => 'W70102','higherOfficeId' => '282','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '285','workPlaceIncrementId' => '295','officeNo' => 'W70103','higherOfficeId' => '282','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '286','workPlaceIncrementId' => '296','officeNo' => 'W70200','higherOfficeId' => '7','districtId' => '5','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '287','workPlaceIncrementId' => '297','officeNo' => 'W70201','higherOfficeId' => '286','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '288','workPlaceIncrementId' => '298','officeNo' => 'W70202','higherOfficeId' => '286','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '289','workPlaceIncrementId' => '299','officeNo' => 'W70203','higherOfficeId' => '286','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '290','workPlaceIncrementId' => '300','officeNo' => 'W70300','higherOfficeId' => '7','districtId' => '5','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '291','workPlaceIncrementId' => '301','officeNo' => 'W70301','higherOfficeId' => '290','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '292','workPlaceIncrementId' => '302','officeNo' => 'W70302','higherOfficeId' => '290','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '293','workPlaceIncrementId' => '303','officeNo' => 'W70400','higherOfficeId' => '7','districtId' => '5','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '294','workPlaceIncrementId' => '304','officeNo' => 'W70401','higherOfficeId' => '293','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '295','workPlaceIncrementId' => '305','officeNo' => 'W70402','higherOfficeId' => '293','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '296','workPlaceIncrementId' => '306','officeNo' => 'W70403','higherOfficeId' => '293','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '297','workPlaceIncrementId' => '307','officeNo' => 'W70500','higherOfficeId' => '7','districtId' => '5','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '298','workPlaceIncrementId' => '308','officeNo' => 'W70501','higherOfficeId' => '297','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '299','workPlaceIncrementId' => '309','officeNo' => 'W70502','higherOfficeId' => '297','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '300','workPlaceIncrementId' => '310','officeNo' => 'W70503','higherOfficeId' => '297','districtId' => '5','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '301','workPlaceIncrementId' => '311','officeNo' => 'W70600','higherOfficeId' => '7','districtId' => '25','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '302','workPlaceIncrementId' => '312','officeNo' => 'W70601','higherOfficeId' => '301','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '303','workPlaceIncrementId' => '313','officeNo' => 'W70602','higherOfficeId' => '301','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '304','workPlaceIncrementId' => '314','officeNo' => 'W70603','higherOfficeId' => '301','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '305','workPlaceIncrementId' => '315','officeNo' => 'W70604','higherOfficeId' => '301','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '306','workPlaceIncrementId' => '316','officeNo' => 'W70700','higherOfficeId' => '7','districtId' => '25','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '307','workPlaceIncrementId' => '317','officeNo' => 'W70701','higherOfficeId' => '306','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '308','workPlaceIncrementId' => '318','officeNo' => 'W70702','higherOfficeId' => '306','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '309','workPlaceIncrementId' => '319','officeNo' => 'W70703','higherOfficeId' => '306','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '310','workPlaceIncrementId' => '320','officeNo' => 'W70704','higherOfficeId' => '306','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '311','workPlaceIncrementId' => '321','officeNo' => 'W70705','higherOfficeId' => '306','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '312','workPlaceIncrementId' => '322','officeNo' => 'W70800','higherOfficeId' => '7','districtId' => '25','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '313','workPlaceIncrementId' => '323','officeNo' => 'W70801','higherOfficeId' => '312','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '314','workPlaceIncrementId' => '324','officeNo' => 'W70802','higherOfficeId' => '312','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '315','workPlaceIncrementId' => '325','officeNo' => 'W70803','higherOfficeId' => '312','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '316','workPlaceIncrementId' => '326','officeNo' => 'W70900','higherOfficeId' => '7','districtId' => '25','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '317','workPlaceIncrementId' => '327','officeNo' => 'W70901','higherOfficeId' => '316','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '318','workPlaceIncrementId' => '328','officeNo' => 'W70902','higherOfficeId' => '316','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '319','workPlaceIncrementId' => '329','officeNo' => 'W71000','higherOfficeId' => '7','districtId' => '25','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '320','workPlaceIncrementId' => '330','officeNo' => 'W71001','higherOfficeId' => '319','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '321','workPlaceIncrementId' => '331','officeNo' => 'W71100','higherOfficeId' => '7','districtId' => '25','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '322','workPlaceIncrementId' => '332','officeNo' => 'W71101','higherOfficeId' => '321','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '323','workPlaceIncrementId' => '333','officeNo' => 'W71102','higherOfficeId' => '321','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '324','workPlaceIncrementId' => '334','officeNo' => 'W71103','higherOfficeId' => '321','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '325','workPlaceIncrementId' => '335','officeNo' => 'W71200','higherOfficeId' => '7','districtId' => '25','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '326','workPlaceIncrementId' => '336','officeNo' => 'W71201','higherOfficeId' => '325','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '327','workPlaceIncrementId' => '337','officeNo' => 'W71202','higherOfficeId' => '325','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '328','workPlaceIncrementId' => '338','officeNo' => 'W71203','higherOfficeId' => '325','districtId' => '25','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '329','workPlaceIncrementId' => '339','officeNo' => 'W71300','higherOfficeId' => '7','districtId' => '4','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '330','workPlaceIncrementId' => '340','officeNo' => 'W71301','higherOfficeId' => '329','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '331','workPlaceIncrementId' => '341','officeNo' => 'W71302','higherOfficeId' => '329','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '332','workPlaceIncrementId' => '342','officeNo' => 'W71303','higherOfficeId' => '329','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '333','workPlaceIncrementId' => '343','officeNo' => 'W71400','higherOfficeId' => '7','districtId' => '4','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '334','workPlaceIncrementId' => '344','officeNo' => 'W71401','higherOfficeId' => '333','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '335','workPlaceIncrementId' => '345','officeNo' => 'W71402','higherOfficeId' => '333','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '336','workPlaceIncrementId' => '346','officeNo' => 'W71500','higherOfficeId' => '7','districtId' => '4','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '337','workPlaceIncrementId' => '347','officeNo' => 'W71501','higherOfficeId' => '336','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '338','workPlaceIncrementId' => '348','officeNo' => 'W71502','higherOfficeId' => '336','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '339','workPlaceIncrementId' => '349','officeNo' => 'W71600','higherOfficeId' => '7','districtId' => '4','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '340','workPlaceIncrementId' => '350','officeNo' => 'W71601','higherOfficeId' => '339','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '341','workPlaceIncrementId' => '351','officeNo' => 'W71602','higherOfficeId' => '339','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '342','workPlaceIncrementId' => '352','officeNo' => 'W71603','higherOfficeId' => '339','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '343','workPlaceIncrementId' => '353','officeNo' => 'W71700','higherOfficeId' => '7','districtId' => '4','provinceId' => '8','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '344','workPlaceIncrementId' => '354','officeNo' => 'W71701','higherOfficeId' => '343','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '345','workPlaceIncrementId' => '355','officeNo' => 'W71702','higherOfficeId' => '343','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '346','workPlaceIncrementId' => '356','officeNo' => 'W71703','higherOfficeId' => '343','districtId' => '4','provinceId' => '8','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '347','workPlaceIncrementId' => '357','officeNo' => 'W80100','higherOfficeId' => '8','districtId' => '9','provinceId' => '3','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '348','workPlaceIncrementId' => '358','officeNo' => 'W80101','higherOfficeId' => '347','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '349','workPlaceIncrementId' => '359','officeNo' => 'W80102','higherOfficeId' => '347','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '350','workPlaceIncrementId' => '360','officeNo' => 'W80103','higherOfficeId' => '347','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '351','workPlaceIncrementId' => '361','officeNo' => 'W80200','higherOfficeId' => '8','districtId' => '9','provinceId' => '3','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '352','workPlaceIncrementId' => '362','officeNo' => 'W80201','higherOfficeId' => '351','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '353','workPlaceIncrementId' => '363','officeNo' => 'W80202','higherOfficeId' => '351','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '354','workPlaceIncrementId' => '364','officeNo' => 'W80203','higherOfficeId' => '351','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '355','workPlaceIncrementId' => '365','officeNo' => 'W80204','higherOfficeId' => '351','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '356','workPlaceIncrementId' => '366','officeNo' => 'W80205','higherOfficeId' => '351','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '357','workPlaceIncrementId' => '367','officeNo' => 'W80300','higherOfficeId' => '8','districtId' => '9','provinceId' => '3','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '358','workPlaceIncrementId' => '368','officeNo' => 'W80301','higherOfficeId' => '357','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '359','workPlaceIncrementId' => '369','officeNo' => 'W80302','higherOfficeId' => '357','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '360','workPlaceIncrementId' => '370','officeNo' => 'W80303','higherOfficeId' => '357','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '361','workPlaceIncrementId' => '371','officeNo' => 'W80304','higherOfficeId' => '357','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '362','workPlaceIncrementId' => '372','officeNo' => 'W80400','higherOfficeId' => '8','districtId' => '9','provinceId' => '3','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '363','workPlaceIncrementId' => '373','officeNo' => 'W80401','higherOfficeId' => '362','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '364','workPlaceIncrementId' => '374','officeNo' => 'W80402','higherOfficeId' => '362','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '365','workPlaceIncrementId' => '375','officeNo' => 'W80403','higherOfficeId' => '362','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '366','workPlaceIncrementId' => '376','officeNo' => 'W80404','higherOfficeId' => '362','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '367','workPlaceIncrementId' => '377','officeNo' => 'W80500','higherOfficeId' => '8','districtId' => '9','provinceId' => '3','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '368','workPlaceIncrementId' => '378','officeNo' => 'W80501','higherOfficeId' => '367','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '369','workPlaceIncrementId' => '379','officeNo' => 'W80502','higherOfficeId' => '367','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '370','workPlaceIncrementId' => '380','officeNo' => 'W80503','higherOfficeId' => '367','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '371','workPlaceIncrementId' => '381','officeNo' => 'W80600','higherOfficeId' => '8','districtId' => '9','provinceId' => '3','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '372','workPlaceIncrementId' => '382','officeNo' => 'W80601','higherOfficeId' => '371','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '373','workPlaceIncrementId' => '383','officeNo' => 'W80602','higherOfficeId' => '371','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '374','workPlaceIncrementId' => '384','officeNo' => 'W80603','higherOfficeId' => '371','districtId' => '9','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '375','workPlaceIncrementId' => '385','officeNo' => 'W80700','higherOfficeId' => '8','districtId' => '8','provinceId' => '3','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '376','workPlaceIncrementId' => '386','officeNo' => 'W80701','higherOfficeId' => '375','districtId' => '8','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '377','workPlaceIncrementId' => '387','officeNo' => 'W80702','higherOfficeId' => '375','districtId' => '8','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '378','workPlaceIncrementId' => '388','officeNo' => 'W80703','higherOfficeId' => '375','districtId' => '8','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '379','workPlaceIncrementId' => '389','officeNo' => 'W80704','higherOfficeId' => '375','districtId' => '8','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '380','workPlaceIncrementId' => '390','officeNo' => 'W80705','higherOfficeId' => '375','districtId' => '8','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '381','workPlaceIncrementId' => '391','officeNo' => 'W80800','higherOfficeId' => '8','districtId' => '8','provinceId' => '3','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '382','workPlaceIncrementId' => '392','officeNo' => 'W80801','higherOfficeId' => '381','districtId' => '8','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '383','workPlaceIncrementId' => '393','officeNo' => 'W80802','higherOfficeId' => '381','districtId' => '8','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '384','workPlaceIncrementId' => '394','officeNo' => 'W80803','higherOfficeId' => '381','districtId' => '8','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '385','workPlaceIncrementId' => '395','officeNo' => 'W80804','higherOfficeId' => '381','districtId' => '8','provinceId' => '3','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '386','workPlaceIncrementId' => '396','officeNo' => 'W90100','higherOfficeId' => '9','districtId' => '15','provinceId' => '2','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '387','workPlaceIncrementId' => '397','officeNo' => 'W90101','higherOfficeId' => '386','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '388','workPlaceIncrementId' => '398','officeNo' => 'W90102','higherOfficeId' => '386','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '389','workPlaceIncrementId' => '399','officeNo' => 'W90103','higherOfficeId' => '386','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '390','workPlaceIncrementId' => '400','officeNo' => 'W90104','higherOfficeId' => '386','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '391','workPlaceIncrementId' => '401','officeNo' => 'W90105','higherOfficeId' => '386','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '392','workPlaceIncrementId' => '402','officeNo' => 'W90200','higherOfficeId' => '9','districtId' => '15','provinceId' => '2','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '393','workPlaceIncrementId' => '403','officeNo' => 'W90201','higherOfficeId' => '392','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '394','workPlaceIncrementId' => '404','officeNo' => 'W90202','higherOfficeId' => '392','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '395','workPlaceIncrementId' => '405','officeNo' => 'W90203','higherOfficeId' => '392','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '396','workPlaceIncrementId' => '406','officeNo' => 'W90300','higherOfficeId' => '9','districtId' => '15','provinceId' => '2','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '397','workPlaceIncrementId' => '407','officeNo' => 'W90301','higherOfficeId' => '396','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '398','workPlaceIncrementId' => '408','officeNo' => 'W90302','higherOfficeId' => '396','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '399','workPlaceIncrementId' => '409','officeNo' => 'W90303','higherOfficeId' => '396','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '400','workPlaceIncrementId' => '410','officeNo' => 'W90304','higherOfficeId' => '396','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '401','workPlaceIncrementId' => '411','officeNo' => 'W90305','higherOfficeId' => '396','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '402','workPlaceIncrementId' => '412','officeNo' => 'W90400','higherOfficeId' => '9','districtId' => '15','provinceId' => '2','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '403','workPlaceIncrementId' => '413','officeNo' => 'W90401','higherOfficeId' => '402','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '404','workPlaceIncrementId' => '414','officeNo' => 'W90402','higherOfficeId' => '402','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '405','workPlaceIncrementId' => '415','officeNo' => 'W90403','higherOfficeId' => '402','districtId' => '15','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '406','workPlaceIncrementId' => '416','officeNo' => 'W90500','higherOfficeId' => '9','districtId' => '16','provinceId' => '2','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '407','workPlaceIncrementId' => '417','officeNo' => 'W90501','higherOfficeId' => '406','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '408','workPlaceIncrementId' => '418','officeNo' => 'W90502','higherOfficeId' => '406','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '409','workPlaceIncrementId' => '419','officeNo' => 'W90503','higherOfficeId' => '406','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '410','workPlaceIncrementId' => '420','officeNo' => 'W90504','higherOfficeId' => '406','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '411','workPlaceIncrementId' => '421','officeNo' => 'W91000','higherOfficeId' => '9','districtId' => '16','provinceId' => '2','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '412','workPlaceIncrementId' => '422','officeNo' => 'W91001','higherOfficeId' => '411','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '413','workPlaceIncrementId' => '423','officeNo' => 'W91002','higherOfficeId' => '411','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '414','workPlaceIncrementId' => '424','officeNo' => 'W91003','higherOfficeId' => '411','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '415','workPlaceIncrementId' => '425','officeNo' => 'W91100','higherOfficeId' => '9','districtId' => '16','provinceId' => '2','officeTypeId' => '2','active' => '1'),
            array('incrementId' => '416','workPlaceIncrementId' => '426','officeNo' => 'W91101','higherOfficeId' => '415','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '417','workPlaceIncrementId' => '427','officeNo' => 'W91102','higherOfficeId' => '415','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '418','workPlaceIncrementId' => '428','officeNo' => 'W91103','higherOfficeId' => '415','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '419','workPlaceIncrementId' => '429','officeNo' => 'W91104','higherOfficeId' => '415','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1'),
            array('incrementId' => '420','workPlaceIncrementId' => '430','officeNo' => 'W91105','higherOfficeId' => '415','districtId' => '16','provinceId' => '2','officeTypeId' => '3','active' => '1')
        );





        foreach ($data as $item) {
            // find WorkPlace by incrementId
            $workPlace = WorkPlace::where('incrementId', $item['workPlaceIncrementId'])->first();
            //dd($workPlace->id, $item);
            if ($workPlace) {
                $item['workPlaceId'] = $workPlace->id; // assign UUID foreign key
                $office = Office::where('incrementId', $item['higherOfficeId'])->first();
                if ($office) {
                    $item['higherOfficeId'] = $office->id; // assign UUID foreign key
                } else {
                    $item['higherOfficeId'] = null; // assign null if not found
                }
            } else {
                continue; // skip if not found
            }
            //dump($item);
            Office::create($item);
        }
    }
}
